# Generated by Django 5.2.6 on 2025-09-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slangword',
            fields=[
                ('slangword_id', models.AutoField(primary_key=True, serialize=False)),
                ('kata', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stopword',
            fields=[
                ('stopword_id', models.AutoField(primary_key=True, serialize=False)),
                ('kata', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teks',
            fields=[
                ('teks_id', models.AutoField(primary_key=True, serialize=False)),
                ('teks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preprocessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_folding', models.TextField(blank=True, null=True)),
                ('tokenisasi', models.TextField(blank=True, null=True)),
                ('stopword_removal', models.TextField(blank=True, null=True)),
                ('slangword_removal', models.TextField(blank=True, null=True)),
                ('stemming', models.TextField(blank=True, null=True)),
                ('teks_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miningApp.teks')),
            ],
        ),
    ]
