# Generated by Django 5.2.6 on 2025-09-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miningApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slangword',
            name='kata_baku',
            field=models.TextField(blank=True, null=True),
        ),
    ]
